# Generated by Django 5.0.6 on 2024-05-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
