# Generated by Django 5.0.6 on 2024-06-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_bloguser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
