# Generated by Django 5.0.6 on 2024-07-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_bloguser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='IMG_0254.jpg', null=True, upload_to='media/profiles/'),
        ),
    ]
